language: python
sudo: required

python:
  - 3.6

addons:
  apt_packages:
    - pandoc

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
  

script:
  - python -m pytest --cov=xlogit

after_sucess:
  - coveralls
